### ISSUE TITLE
check_isitdownrightnow: URL and output changed

### ISSUE THREAD

**Issue by waja** [wopfel/monitoring-plugins#2]
``` sh
$ ./check_isitdownrightnow -s www.google.com
WARNING: Site 'www.google.com' seems to be down according to isitdownrightnow.com. Message: Www.google.com is DOWN  for everyone..
```

This is due isitdownrightnow.com changed it's URL and the site layout.

**Comment by wopfel** [comment]
Thank you for the hint. I'll look into that...

**Comment by wopfel** [comment]
When I enter `www.google.com` on the web site, the check is run against google.com. It seems the `www.` is automatically stripped off. I guess you have to specify the site without `www.`. But I'm unsure if this is true for all sites.
The real check is done by check.php and that didn't change obviously.

``` sh
$ ./check_isitdownrightnow -s google.com
OK: Site 'google.com' is up and reachable according to isitdownrightnow.com. | response_time=8.04ms
```
